# Generated by Django 5.0.3 on 2024-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='images/fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagemSecundaria',
            field=models.ImageField(blank=True, null=True, upload_to='images/fotos/%Y/%m/%d/'),
        ),
    ]
