# Generated by Django 5.0.3 on 2024-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_cor_tamanho_produto_colecao_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='coresDisponiveis',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanhosDisponiveis',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_offWhite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_preto',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Cor',
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
