# Generated by Django 5.0.3 on 2024-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_coresdisponiveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor_azul',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_vermelha',
            field=models.BooleanField(default=True),
        ),
    ]
