# Generated by Django 5.0.3 on 2024-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_cor_azul_produto_cor_vermelha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor_azul',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor_offWhite',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor_preto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor_vermelha',
        ),
        migrations.AddField(
            model_name='produto',
            name='cores',
            field=models.JSONField(default=list),
        ),
    ]
