# Generated by Django 5.0.3 on 2024-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_produto_cor_azul_remove_produto_cor_offwhite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='colecao',
            field=models.CharField(choices=[('none', 'Nenhuma'), ('colecao2', 'Coleção 2'), ('colecao2', 'Coleção 2'), ('colecao2', 'Coleção 2')], default='none', max_length=100),
        ),
    ]
