# Generated by Django 5.0.3 on 2024-03-22 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='Descrição da Coleção')),
                ('lancamento', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='colecao',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='produtos.colecoes'),
        ),
    ]
