# Generated by Django 5.0.3 on 2024-03-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produto_colecao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colecoes',
            new_name='Colecao',
        ),
    ]
