# Generated by Django 5.0.3 on 2024-03-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_rename_colecoes_colecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cores',
            field=models.JSONField(default={'cores': [{'codigo': '#000000', 'nome': 'Preto'}, {'codigo': '#FFFFFF', 'nome': 'Branco'}]}),
        ),
    ]
