# Generated by Django 5.0.3 on 2024-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_alter_produto_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cores',
            field=models.JSONField(default={'cores': [{'codigo': '#000000', 'nome': 'Preto'}, {'codigo': '#FFFFFF', 'nome': 'Off-White'}, {'codigo': '#FFFFFF', 'nome': 'Branco'}]}),
        ),
    ]
