# Generated by Django 5.0.3 on 2024-03-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_alter_produto_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Oversized', 'OVERSIZED'), ('Sweater', 'SWEATERS')], default=None, max_length=10),
        ),
    ]
