# Generated by Django 5.0.3 on 2024-03-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_produto_ativo_produto_outlet_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='imagem',
            field=models.ImageField(default=None, upload_to='images/fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='imagemSecundaria',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/fotos/%Y/%m/%d/'),
        ),
    ]
