# Generated by Django 5.0.3 on 2024-03-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_colecao_ativo_colecao_imagem_colecao_imagem2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecao',
            old_name='imagem2',
            new_name='imagemSecundaria',
        ),
    ]
