# Generated by Django 5.0.3 on 2024-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_remove_produto_ativo_remove_produto_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('OFF-WHITE', 'Off-White'), ('MARROM', 'Marrom')], default='PRETO', max_length=20),
        ),
    ]
