# Generated by Django 5.0.3 on 2024-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_variacaoproduto_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('MARROM', 'Marrom')], default='PRETO', max_length=20),
        ),
    ]
