# Generated by Django 5.0.3 on 2024-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secao',
            name='imagem',
        ),
        migrations.AddField(
            model_name='secao',
            name='imagem1',
            field=models.ImageField(default=None, upload_to='images/secoes/'),
        ),
        migrations.AddField(
            model_name='secao',
            name='imagem2',
            field=models.ImageField(default=None, upload_to='images/secoes/'),
        ),
        migrations.AddField(
            model_name='secao',
            name='imagem3',
            field=models.ImageField(default=None, upload_to='images/secoes/'),
        ),
    ]
