# Generated by Django 5.0.3 on 2024-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_secao_imagem_secao_imagem1_secao_imagem2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='posicao',
            field=models.BooleanField(default=True),
        ),
    ]
